### ISSUE TITLE
Test "TXT register space accessible" should not check if HeapBase is 0

### ISSUE THREAD

**Issue by PatrickRudolph** [9elements/converged-security-suite#122]
It looks like HeapBase is left 0 if firmware doesn't do TXT initialisation. However the TXT space *is* accessible in that case as it doesn't read as ~0, so the test should return success.

**Comment by ChriMarMe** [comment]
So remove this check completly?

**Comment by PatrickRudolph** [comment]
maybe there's another non-zero field that can be tested instead TXT.PUBLIC.KEY maybe?

**Comment by zaolin** [comment]
I think the error comes from strict devmem case

**Comment by PatrickRudolph** [comment]
> I think the error comes from strict devmem case

that should generate an internal error

**Comment by ChriMarMe** [comment]
#158 Addresses this issue
