### ISSUE TITLE
IA32DebugInterfaceEnabledOrLocked() caller use wrong parameter sequence

### ISSUE THREAD

**Issue by jonzhang-fb** [9elements/converged-security-suite#131]
In IA32DebugInterfaceEnabledOrLocked() (bool, bool, bool, error), it:
  return enabled, locked, pchStrap, nil

The caller though take the return with wrong parameter sequence:
// IA32DebugInterfaceLockedDisabled checks if IA32 debug interface is locked
func IA32DebugInterfaceLockedDisabled(txtAPI hwapi.APIInterfaces) (bool, error, error) {
  locked, pchStrap, enabled, err := txtAPI.IA32DebugInterfaceEnabledOrLocked()

**Comment by zaolin** [comment]
@jonzhang-fb Confirmed, fixed with #132
