### ISSUE TITLE
cmd/bg-prov: Add validation command for km and bpm

### ISSUE THREAD

**Issue by ChriMarMe** [9elements/converged-security-suite#174]
### KM and BPM validation command needed

Introduce command which checks the sanity of KM and BPM. This should include checks of every field of KM and BPM structure.
The unterlaying function can be used in ParseKM and ParseBPM functions to reject invalid binaries and in SetKM / GenerateBPM functions to reject invalid configurations.

**Comment by ChriMarMe** [comment]
#218 waiting for review

**Comment by zaolin** [comment]
#346
