### ISSUE TITLE
intel/manifest/metadata is missing cryptographic algorithms

### ISSUE THREAD

**Issue by zaolin** [9elements/converged-security-suite#180]
Multiple show commands report something like this: Alg?<18>
bg-prov: error: couldn't match requested hash algorithm: 0x416c673f3c31383e

**Comment by ChriMarMe** [comment]
Problem is the ReadData function of BPM, if there is a certain structure in the image, the parsing fails miserably.

**Comment by xaionaro** [comment]
How to reproduce the problem?
