### ISSUE TITLE
Fix signature pretty print for BPM and KM

### ISSUE THREAD

**Issue by zaolin** [9elements/converged-security-suite#187]
* Pretty print the same structure should just have one name.
* Currently, PSME, Signature, Key And Signature, KeyAndSignature are used

**Comment by ChriMarMe** [comment]
Signature, KeySignature, "Key" and "Signature" are four different structures. 

PMSE is the fieldname of BPM and holds a structure of Signature. The Signature struct holds one substruct: "KeySignature". KeySignature holds zwo struct: "Key" and "Signature"

In KM, we dont have a the first most upper level structure of "Signature". So KM and BPM Signature structs are printed the same, but in BPM it is held in a extra structure with the "structInfo" field.
