### ISSUE TITLE
Bug - tools.CalcImageOffset

### ISSUE THREAD

**Issue by ChriMarMe** [9elements/converged-security-suite#220]
When using tools.CalcImageOffset(image, addr) with a coreboot firmware image I get a warning. 
```
2021/04/09 08:12:22 error parsing ME Flash Partition Table: ME Flash Partition Table signature 0x24465054 not found: first 20 bytes are:
00000000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
00000010 00 30 00 00 |.0..|
```

Is this intended? Can we fix this?

**Comment by ChriMarMe** [comment]
This is related to fiano package. Supressed the warning now.

**Comment by xaionaro** [comment]
A better fix: https://github.com/linuxboot/fiano/pull/331
