### ISSUE TITLE
Test41SINITMatchesCPU allow no SINIT ACM in memory

### ISSUE THREAD

**Issue by siro20** [9elements/converged-security-suite#24]
The SINIT ACM may optionally provided by the firmware.
Don't fail in Test41SINITMatchesCPU if no SINIT ACM was provided by the firmware.

**Comment by siro20** [comment]
This is only the case if txt-suite is run before tboot, or on a platform without tboot, as tboot loads the SINIT ACM into memory, too.

**Comment by ChriMarMe** [comment]
Test changed to not required.

**Comment by PatrickRudolph** [comment]
the corre

**Comment by ChriMarMe** [comment]
I think i fixed that already
