### ISSUE TITLE
bg-suite CLI improvements

### ISSUE THREAD

**Issue by orangecms** [9elements/converged-security-suite#377]
some proposals:

- add a set for running the non-runtime checks only (makes sense when providing a file from another system etc)
- supply the list of tests to run directly instead of `single` and supplying an extra number; e.g., `--set="1,2,3"`

i.e., have the sets
- `all` as of now
- `static` (no runtime checks)
- `runtime` (only runtime checks; does that make sense even?)
- list by numbers, like `1,3,5` etc

**Comment by walterchris** [comment]
Like #379 ?

**Comment by orangecms** [comment]
> Like #379 ?

Neat, nailed it, yea! :)
